### PR TITLE
Leading zeros in gem counter removed, quota rainbow effect on 100%

### PR DESCRIPTION
**Pull request by main-gi**
Modifies the same file, playGui.cs, so they're in one pull request.

Leading zeros are gone: "003/006" becomes "3/6". The UI is shifted so it doesn't look like "3/ 6", and it works for Quota as well. Quota also has a new fancy hue shifting animation on getting a 100% quota (which undoes itself if you lose progress from 100% or leave the level).

Visual preview:

https://cdn.discordapp.com/attachments/701856989218603118/812179584073072730/Quota_100_Hypernova_Gem_Counter.mp4

This is a resubmission just to clean up comments and previous commit history.

### CODE REVIEW

**Comment by HiGuyMB** [comment]
I agree with cleaning up the leading zeroes in the gem counter, but I think rainbow effects should be reserved for easter egg-type features only (hidden and activated if you know how), since they are rather gaudy. If you want to split that out of this PR I'd be okay including just the gem counter stuff.

**Comment by main-gi** [comment]
I'm not so invested in the rainbow effect itself so much as that I felt that 100% quota was underwhelming, you only get a message box of "you aced the level" and that's it (and IMO, the final counter of say "40/20/40" is really unsatisfying). So the rainbow effect is one of the more noticeable changes, and it is _hidden_, although yeah, not easter-egg level hidden.

I'd like to change the rainbow instead to a 'golden' effect, with lightness/saturation modulated so it looks shining, if you agree with it. Otherwise I'll change it to only include the gem counter stuff.

**Comment by adierking** [comment]
> Otherwise I'll change it to only include the gem counter stuff.

Let's just do that.

**Comment by main-gi** [comment]
Very disappointing and terrible, 0/10. Quota 100% most neglected gamemode.

**Pull request closed without merging**
