### PR TITLE
MBU Red Gems

### PR DESCRIPTION
**Pull request by BlastedMarble**
In the original Marble Blast Ultra, all the gems are colored red every time you play a level. It is not the case in PQ. Having all the gems be red is the icing on the cake needed to make the PQ versions of these levels faithful to the originals.

### CODE REVIEW

**Comment by adierking** [comment]
Thanks for contributing!

This commit looks like it's (accidentally?) adding a bunch of advanced and intermediate levels into the beginner/ directory. Can you please fix this?

**Comment by BlastedMarble** [comment]
That was my mistake. Should I redo this request by pulling 3 additional requests, one for each difficulty?

**Comment by BlastedMarble** [comment]
> Thanks for contributing!
> 
> This commit looks like it's (accidentally?) adding a bunch of advanced and intermediate levels into the beginner/ directory. Can you please fix this?

Fixed.

**Comment by JeffProgrammer** [comment]
Looks good. @HiGuyMB / @adierking if alls good I can hit the big squash and merge btn.

**Review by JeffProgrammer — APPROVED** [review]

**Comment by BlastedMarble** [comment]
Thank you.

**Comment by adierking** [comment]
> Looks good. @HiGuyMB / @adierking if alls good I can hit the big squash and merge btn.

Yeah looks good now. Make sure to cherry-pick into the internal repo after merging.

**Pull request merged**
